import XCTest
@testable import TapScore

/// Pins the one thing the native create flow cannot get subtly wrong: the JSON
/// it POSTs must be the JSON the WEB posts for the same choices.
///
/// **How the expectations were derived.** They were not written by hand — a
/// hand-written expectation would only pin what the iOS author *believed* the
/// web sends, which is exactly the belief under test. `WebDraftFixtures.swift`
/// is generated by `ios/TapScoreTests/Create/derive-web-fixtures.ts`, which
/// imports the real web client (`src/create/setup.service.ts`), seeds it with
/// the real server format catalog (`server/domain/formats`), drives it through
/// the same choices as each test below, and captures the draft it hands to
/// `api.friendlyRounds.create`. The same file also carries the descriptors that
/// run was made against (`catalogJSON`), so the native `FormatCatalog` derives
/// its shapes from the identical bytes rather than a re-typed copy.
///
/// Regenerate with `bun run ios/TapScoreTests/Create/derive-web-fixtures.ts`.
/// A diff in the generated file IS the parity break, visible in review.
///
/// `playedAt` is frozen in the generator (both clients otherwise stamp "today",
/// which would rot the fixture overnight); the drafts below are built with the
/// same literal, so the field is still asserted.
final class CreateDraftParityTests: XCTestCase {
    private var catalog: FormatCatalog!

    override func setUpWithError() throws {
        try super.setUpWithError()
        let descriptors = try JSONDecoder().decode(
            [FormatDescriptor].self,
            from: Data(WebDraftFixtures.catalogJSON.utf8))
        catalog = FormatCatalog(descriptors: descriptors)
    }

    override func tearDown() {
        catalog = nil
        super.tearDown()
    }

    // MARK: - Scenarios

    func testStablefordIndividualThreePlayersMatchesWeb() throws {
        try assertParity(
            formatId: "stableford_individual",
            indices: [12, 18.4, -2.4],
            fixture: WebDraftFixtures.stablefordIndividualThree)
    }

    func testTalibanBetterBallFourPlayersMatchesWeb() throws {
        try assertParity(
            formatId: "taliban_better_ball",
            indices: [12, 12, 12, 12],
            fixture: WebDraftFixtures.talibanBetterBallFour)
    }

    func testStablefordBetterBallFourPlayersMatchesWeb() throws {
        try assertParity(
            formatId: "stableford_better_ball",
            indices: [12, 12, 12, 12],
            fixture: WebDraftFixtures.stablefordBetterBallFour)
    }

    func testKopenhamnareFourPlayersMatchesWeb() throws {
        try assertParity(
            formatId: "kopenhamnare_individual",
            indices: [12, 12, 12, 12],
            fixture: WebDraftFixtures.kopenhamnareFour)
    }

    func testUmbrellaIndividualThreePlayersMatchesWeb() throws {
        try assertParity(
            formatId: "umbrella_individual",
            indices: [12, 12, 12],
            fixture: WebDraftFixtures.umbrellaIndividualThree)
    }

    /// A ball-count minimum with no maximum and no team grouping — the shape no
    /// other scenario has (Stableford individual declares no `slotBallCount` at
    /// all, Köpenhamnare bounds it at both ends).
    func testMatchPlayIndividualTwoPlayersMatchesWeb() throws {
        try assertParity(
            formatId: "match_play_individual",
            indices: [12, 12],
            fixture: WebDraftFixtures.matchPlayIndividualTwo)
    }

    /// Grouping with a declared team COUNT and a wide team size — Stableford
    /// better-ball declares a size but no count, and the two seed differently.
    func testMatchPlayBetterBallFourPlayersMatchesWeb() throws {
        try assertParity(
            formatId: "match_play_better_ball",
            indices: [12, 12, 12, 12],
            fixture: WebDraftFixtures.matchPlayBetterBallFour)
    }

    /// Taliban's shape plus per-ball metadata (GIR), which is what excludes a
    /// format from side aggregation — so it is a branch, not a label.
    func testUmbrella4BallFourPlayersMatchesWeb() throws {
        try assertParity(
            formatId: "umbrella_4_ball",
            indices: [12, 12, 12, 12],
            fixture: WebDraftFixtures.umbrella4BallFour)
    }

    // MARK: - Properties the fixtures make concrete

    /// A side format's subjects are its sides ONLY. Four players in a
    /// better-ball must not also arrive as four individual subjects — that is
    /// the double-scoring trap `compose` exists to avoid, and it is the single
    /// most expensive way this port could differ from the web.
    func testSideFormatEmitsNoPlayerSubjects() throws {
        let draft = makeDraft(formatId: "taliban_better_ball", indices: [12, 12, 12, 12])
        let kinds = (draft.formats[0].subjects ?? []).map { subject -> String in
            switch subject {
            case .player: "player"
            case .team: "team"
            }
        }
        XCTAssertEqual(kinds, ["team", "team"])
    }

    /// A ball holding one player is dropped rather than shipped as a one-member
    /// team: the server would refuse it, and the web drops it the same way.
    func testUnderfilledTeamBallIsNotShipped() throws {
        let builder = CreateDraftBuilder(catalog: catalog)
        var game = builder.seedGame(formatId: "taliban_better_ball", rosterCount: 4)
        // Strand p4 on its own ball.
        game.ballByPlayer[3] = 2
        game.ballCount = 3
        let draft = builder.draft(
            courseId: "c1",
            roundType: .full18,
            game: game,
            players: players(indices: [12, 12, 12, 12]),
            playedAt: WebDraftFixtures.playedAt)
        XCTAssertEqual(draft.teams?.count, 1)
        XCTAssertEqual(draft.formats[0].subjects?.count, 1)
    }

    /// A knobless format emits no `formatConfig` key at all — an empty object
    /// would be a wire-shape change the server has to interpret.
    func testKnoblessFormatOmitsFormatConfig() throws {
        let draft = makeDraft(formatId: "stableford_individual", indices: [12, 12])
        XCTAssertNil(draft.formats[0].formatConfig)
    }

    /// `playedAt` is a UTC date, matching the web's
    /// `new Date().toISOString().slice(0, 10)` — not the device's local day.
    func testTodayIsUTC() {
        // 2026-01-02T23:30Z is still 2026-01-02 in UTC and 2026-01-03 in CET+1.
        let date = Date(timeIntervalSince1970: 1_767_396_600)
        XCTAssertEqual(CreateDraftBuilder.today(date), "2026-01-02")
    }

    // MARK: - Helpers

    private func players(indices: [Double]) -> [CreateDraftBuilder.Player] {
        indices.enumerated().map { i, index in
            CreateDraftBuilder.Player(
                name: ["Anna", "Bert", "Cleo", "Dan"][i],
                handicapIndex: index,
                teeId: "tee-y",
                gender: .m,
                ref: .guest("guest-\(i + 1)"))
        }
    }

    private func makeDraft(
        formatId: String,
        indices: [Double]
    ) -> CompetitionsCreateRoundOutputOkDraft {
        let builder = CreateDraftBuilder(catalog: catalog)
        return builder.draft(
            courseId: "c1",
            roundType: .full18,
            game: builder.seedGame(formatId: formatId, rosterCount: indices.count),
            players: players(indices: indices),
            playedAt: WebDraftFixtures.playedAt)
    }

    private func assertParity(
        formatId: String,
        indices: [Double],
        fixture: String,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let draft = makeDraft(formatId: formatId, indices: indices)
        let native = try JSONCanon.text(of: try JSONEncoder().encode(draft))
        let web = try JSONCanon.text(of: Data(fixture.utf8))
        XCTAssertEqual(native, web, "native draft differs from the web's", file: file, line: line)
    }
}

/// Canonical JSON text: keys sorted, numbers normalised, so two encoders'
/// formatting differences cannot masquerade as a parity break — and a real one
/// shows up as a readable line diff in the failure message.
enum JSONCanon {
    static func text(of data: Data) throws -> String {
        render(try JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]))
    }

    private static func render(_ value: Any, indent: String = "") -> String {
        switch value {
        case let dict as [String: Any]:
            let body = dict.keys.sorted().map { key in
                "\(indent)  \(key): \(render(dict[key]!, indent: indent + "  "))"
            }
            return body.isEmpty ? "{}" : "{\n\(body.joined(separator: "\n"))\n\(indent)}"
        case let array as [Any]:
            let body = array.map { "\(indent)  \(render($0, indent: indent + "  "))" }
            return body.isEmpty ? "[]" : "[\n\(body.joined(separator: "\n"))\n\(indent)]"
        case let number as NSNumber:
            // CFBoolean is an NSNumber too; keep true/false readable.
            if CFGetTypeID(number) == CFBooleanGetTypeID() { return number.boolValue ? "true" : "false" }
            let double = number.doubleValue
            return double == double.rounded() && abs(double) < 1e15
                ? String(Int64(double))
                : String(double)
        case let string as String:
            return "\"\(string)\""
        default:
            return "null"
        }
    }
}
