// GENERATED by ios/TapScoreTests/Create/derive-web-fixtures.ts — DO NOT EDIT.
//
// Each fixture is the draft the WEB client (`src/create/setup.service.ts`,
// driven with the real server format catalog) POSTs for the named game and
// roster. `CreateDraftParityTests` asserts the native builder produces the
// same JSON — key order normalised, values verbatim.
//
// Regenerate with:
//   bun run ios/TapScoreTests/Create/derive-web-fixtures.ts

enum WebDraftFixtures {
    /// Every fixture's `playedAt`, frozen so the expectations do not rot
    /// overnight. The test builds its draft with this same date.
    static let playedAt = "2026-01-02"

    /// The server format descriptors these drafts were built against — the same
    /// bytes `GET /setup/formats` serves, narrowed to the formats used below.
    static let catalogJSON = """
    [
      {
        "clientAdapterId": null,
        "configFields": [
          {
            "default": "standard",
            "key": "handicapMode",
            "kind": "select",
            "labels": {
              "en": "Handicap strokes",
              "sv": "Slagtilldelning"
            },
            "options": [
              {
                "labels": {
                  "en": "Full handicap for everyone",
                  "sv": "Full slagtilldelning för alla"
                },
                "value": "standard"
              },
              {
                "labels": {
                  "en": "Lowest handicap plays off scratch",
                  "sv": "Lägsta handicappet spelar utan slag"
                },
                "value": "delta_from_min"
              }
            ]
          }
        ],
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatConfig": {
            "handicapMode": "standard"
          }
        },
        "description": "Three-way per-hole point distribution; highest wins.",
        "id": "kopenhamnare_individual",
        "label": "Split sixes",
        "labels": {
          "en": "Split sixes",
          "sv": "Köpenhamnare"
        },
        "metrics": [
          {
            "direction": "high",
            "id": "points",
            "label": "Points"
          }
        ],
        "preset": {
          "rank": 3,
          "tagline": {
            "en": "Three players share out six points on every hole.",
            "sv": "Tre spelare delar sex poäng på varje hål."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": false,
            "slotBallCount": {
              "max": 3,
              "min": 3
            }
          }
        },
        "resultDisplay": {
          "runningTotals": "normalized"
        },
        "scoresAnyBall": true,
        "scoringMode": "kopenhamnare",
        "teamShape": "individual"
      },
      {
        "clientAdapterId": null,
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          }
        },
        "description": "Best-ball-per-team head-to-head match play.",
        "id": "match_play_better_ball",
        "label": "Better-ball match play",
        "labels": {
          "en": "Better-ball match play",
          "sv": "Bästboll matchspel"
        },
        "metrics": [],
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": true,
            "slotBallCount": {
              "max": 20,
              "min": 4
            },
            "slotTeamGrouping": {
              "teamCount": {
                "max": 2,
                "min": 2
              },
              "teamSize": {
                "max": 10,
                "min": 2
              }
            }
          }
        },
        "resultDisplay": {
          "scoreGridComponentId": "compact-match-grid"
        },
        "scoresAnyBall": true,
        "scoringMode": "match_play",
        "teamShape": "better_ball"
      },
      {
        "clientAdapterId": null,
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          }
        },
        "description": "Head-to-head per hole; pairs balls in supplied order.",
        "id": "match_play_individual",
        "label": "Match play",
        "labels": {
          "en": "Match play",
          "sv": "Matchspel"
        },
        "metrics": [],
        "preset": {
          "rank": 5,
          "tagline": {
            "en": "One against one, hole by hole.",
            "sv": "Man mot man, hål för hål."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": false,
            "slotBallCount": {
              "min": 2,
              "multipleOf": 1
            }
          }
        },
        "resultDisplay": {
          "scoreGridComponentId": "compact-match-grid"
        },
        "scoresAnyBall": true,
        "scoringMode": "match_play",
        "teamShape": "individual"
      },
      {
        "clientAdapterId": null,
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          }
        },
        "description": "Best Stableford score per team per hole.",
        "id": "stableford_better_ball",
        "label": "Better-ball Stableford",
        "labels": {
          "en": "Better-ball Stableford",
          "sv": "Bästboll poängbogey"
        },
        "metrics": [
          {
            "direction": "high",
            "id": "points",
            "label": "Points",
            "pace": {
              "perHole": 2
            }
          }
        ],
        "preset": {
          "rank": 6,
          "tagline": {
            "en": "Play in pairs — the best score on each hole counts.",
            "sv": "Spela två och två – bästa poängen på varje hål räknas."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": true,
            "slotTeamGrouping": {
              "teamSize": {
                "max": 10,
                "min": 2
              }
            }
          }
        },
        "scoresAnyBall": true,
        "scoringMode": "stableford",
        "teamShape": "better_ball"
      },
      {
        "clientAdapterId": null,
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          }
        },
        "description": "Points per hole against net par; highest wins.",
        "id": "stableford_individual",
        "label": "Stableford",
        "labels": {
          "en": "Stableford",
          "sv": "Poängbogey"
        },
        "metrics": [
          {
            "direction": "high",
            "id": "points",
            "label": "Points",
            "pace": {
              "perHole": 2
            }
          }
        ],
        "preset": {
          "rank": 1,
          "tagline": {
            "en": "Points per hole — one bad hole never ruins the round.",
            "sv": "Poäng per hål – ett dåligt hål förstör aldrig ronden."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": false
          }
        },
        "resultDisplay": {
          "scoreGridComponentId": "default-score-grid"
        },
        "scoresAnyBall": true,
        "scoringMode": "stableford",
        "teamShape": "individual"
      },
      {
        "clientAdapterId": null,
        "configFields": [
          {
            "default": "gross",
            "key": "bonusRule",
            "kind": "select",
            "labels": {
              "en": "Bonus scores count as",
              "sv": "Bonuspoäng räknas på"
            },
            "options": [
              {
                "labels": {
                  "en": "Gross",
                  "sv": "Brutto"
                },
                "value": "gross"
              },
              {
                "labels": {
                  "en": "Net",
                  "sv": "Netto"
                },
                "value": "net"
              }
            ]
          }
        ],
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatConfig": {
            "bonusRule": "gross"
          }
        },
        "description": "Team better-ball with weighted birdie/eagle bonus pairs.",
        "id": "taliban_better_ball",
        "label": "Taliban",
        "labels": {
          "en": "Taliban",
          "sv": "Taliban"
        },
        "metrics": [],
        "preset": {
          "rank": 2,
          "tagline": {
            "en": "Two against two — the pair that is behind can catch up fast.",
            "sv": "Två mot två – laget som ligger under kan jaga ikapp snabbt."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": true,
            "slotBallCount": {
              "max": 4,
              "min": 4
            },
            "slotTeamGrouping": {
              "teamCount": {
                "max": 2,
                "min": 2
              },
              "teamSize": {
                "max": 2,
                "min": 2
              }
            }
          }
        },
        "resultDisplay": {
          "scoreGridComponentId": "compact-match-grid"
        },
        "scoresAnyBall": true,
        "scoringMode": "taliban",
        "teamShape": "better_ball"
      },
      {
        "clientAdapterId": null,
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          }
        },
        "description": "Team umbrella with per-player GIR categories.",
        "id": "umbrella_4_ball",
        "label": "Umbrella (4-ball)",
        "labels": {
          "en": "Umbrella (4-ball)",
          "sv": "Umbrella (4-boll)"
        },
        "metrics": [
          {
            "direction": "high",
            "id": "points",
            "label": "Points"
          }
        ],
        "preset": {
          "rank": 8,
          "tagline": {
            "en": "Umbrella in pairs — the best of each pair counts on every hole.",
            "sv": "Umbrella två och två – bästa i paret räknas på varje hål."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": true,
            "slotBallCount": {
              "max": 4,
              "min": 4
            },
            "slotTeamGrouping": {
              "teamCount": {
                "max": 2,
                "min": 2
              },
              "teamSize": {
                "max": 2,
                "min": 2
              }
            }
          },
          "scoreEntry": {
            "metadata": [
              {
                "key": "gir",
                "kind": "boolean",
                "label": "GIR"
              }
            ],
            "strokes": true
          }
        },
        "resultDisplay": {
          "runningTotals": "normalized",
          "scoreGridComponentId": "category-matrix-grid"
        },
        "scoresAnyBall": true,
        "scoringMode": "umbrella",
        "teamShape": "four_ball"
      },
      {
        "clientAdapterId": null,
        "defaults": {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          }
        },
        "description": "Per-hole category points (long-game, fairway, GIR, birdie).",
        "id": "umbrella_individual",
        "label": "Umbrella",
        "labels": {
          "en": "Umbrella",
          "sv": "Umbrella"
        },
        "metrics": [
          {
            "direction": "high",
            "id": "points",
            "label": "Points"
          }
        ],
        "preset": {
          "rank": 7,
          "tagline": {
            "en": "Points for length, fairway, green in regulation and birdie.",
            "sv": "Poäng för längd, fairway, green i regulation och birdie."
          }
        },
        "requirements": {
          "balls": {
            "ballMode": "own",
            "producerCount": {
              "max": 1,
              "min": 1
            },
            "requiresSlotTeamGrouping": false,
            "slotBallCount": {
              "max": 3,
              "min": 3
            }
          },
          "scoreEntry": {
            "metadata": [
              {
                "key": "gir",
                "kind": "boolean",
                "label": "GIR"
              },
              {
                "appliesWhen": {
                  "minPar": 4
                },
                "key": "fairway",
                "kind": "boolean",
                "label": "Fairway"
              }
            ],
            "strokes": true
          }
        },
        "resultDisplay": {
          "runningTotals": "normalized",
          "scoreGridComponentId": "category-matrix-grid"
        },
        "scoringMode": "umbrella",
        "teamShape": "individual"
      }
    ]
    """

    static let stablefordIndividualThree = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatId": "stableford_individual",
          "subjects": [
            {
              "kind": "player",
              "producerDefId": "p1"
            },
            {
              "kind": "player",
              "producerDefId": "p2"
            },
            {
              "kind": "player",
              "producerDefId": "p3"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 18.4,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": -2.4,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18"
    }
    """

    static let talibanBetterBallFour = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatConfig": {
            "bonusRule": "gross"
          },
          "formatId": "taliban_better_ball",
          "subjects": [
            {
              "kind": "team",
              "teamId": "1"
            },
            {
              "kind": "team",
              "teamId": "2"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-4",
            "kind": "guest"
          },
          "producerDefId": "p4",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18",
      "teams": [
        {
          "formation": "custom",
          "id": "1",
          "kind": "multi_ball",
          "label": "Team A",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p1"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p2"
            }
          ]
        },
        {
          "formation": "custom",
          "id": "2",
          "kind": "multi_ball",
          "label": "Team B",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p3"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p4"
            }
          ]
        }
      ]
    }
    """

    static let stablefordBetterBallFour = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatId": "stableford_better_ball",
          "subjects": [
            {
              "kind": "team",
              "teamId": "1"
            },
            {
              "kind": "team",
              "teamId": "2"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-4",
            "kind": "guest"
          },
          "producerDefId": "p4",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18",
      "teams": [
        {
          "formation": "custom",
          "id": "1",
          "kind": "multi_ball",
          "label": "Team A",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p1"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p2"
            }
          ]
        },
        {
          "formation": "custom",
          "id": "2",
          "kind": "multi_ball",
          "label": "Team B",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p3"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p4"
            }
          ]
        }
      ]
    }
    """

    static let kopenhamnareFour = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatConfig": {
            "handicapMode": "standard"
          },
          "formatId": "kopenhamnare_individual",
          "subjects": [
            {
              "kind": "player",
              "producerDefId": "p1"
            },
            {
              "kind": "player",
              "producerDefId": "p2"
            },
            {
              "kind": "player",
              "producerDefId": "p3"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-4",
            "kind": "guest"
          },
          "producerDefId": "p4",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18"
    }
    """

    static let umbrellaIndividualThree = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatId": "umbrella_individual",
          "subjects": [
            {
              "kind": "player",
              "producerDefId": "p1"
            },
            {
              "kind": "player",
              "producerDefId": "p2"
            },
            {
              "kind": "player",
              "producerDefId": "p3"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18"
    }
    """

    static let matchPlayIndividualTwo = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatId": "match_play_individual",
          "subjects": [
            {
              "kind": "player",
              "producerDefId": "p1"
            },
            {
              "kind": "player",
              "producerDefId": "p2"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18"
    }
    """

    static let matchPlayBetterBallFour = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatId": "match_play_better_ball",
          "subjects": [
            {
              "kind": "team",
              "teamId": "1"
            },
            {
              "kind": "team",
              "teamId": "2"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-4",
            "kind": "guest"
          },
          "producerDefId": "p4",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18",
      "teams": [
        {
          "formation": "custom",
          "id": "1",
          "kind": "multi_ball",
          "label": "Team A",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p1"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p2"
            }
          ]
        },
        {
          "formation": "custom",
          "id": "2",
          "kind": "multi_ball",
          "label": "Team B",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p3"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p4"
            }
          ]
        }
      ]
    }
    """

    static let umbrella4BallFour = """
    {
      "courseId": "c1",
      "formats": [
        {
          "allowanceConfig": {
            "pct": 100,
            "type": "flat"
          },
          "formatId": "umbrella_4_ball",
          "subjects": [
            {
              "kind": "team",
              "teamId": "1"
            },
            {
              "kind": "team",
              "teamId": "2"
            }
          ]
        }
      ],
      "playedAt": "2026-01-02",
      "producers": [
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-1",
            "kind": "guest"
          },
          "producerDefId": "p1",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-2",
            "kind": "guest"
          },
          "producerDefId": "p2",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-3",
            "kind": "guest"
          },
          "producerDefId": "p3",
          "teeId": "tee-y"
        },
        {
          "gender": "M",
          "handicapIndex": 12,
          "playerRef": {
            "id": "guest-4",
            "kind": "guest"
          },
          "producerDefId": "p4",
          "teeId": "tee-y"
        }
      ],
      "roundType": "full_18",
      "teams": [
        {
          "formation": "custom",
          "id": "1",
          "kind": "multi_ball",
          "label": "Team A",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p1"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p2"
            }
          ]
        },
        {
          "formation": "custom",
          "id": "2",
          "kind": "multi_ball",
          "label": "Team B",
          "members": [
            {
              "allowancePct": 100,
              "producerDefId": "p3"
            },
            {
              "allowancePct": 100,
              "producerDefId": "p4"
            }
          ]
        }
      ]
    }
    """
}
