// Production reference-data seed — idempotent, DB_PATH-aware.
//
// Seeds ONLY real course data (clubs + courses + rated tees) into the DB at
// DB_PATH. No players, no rounds: this is a no-login on-course app, and
// scorecards are produced by actually playing rounds in the UI. Safe to
// re-run — every step is find-or-create, so a second run is a no-op.
//
// Course data is extracted from the legacy golf-serie DB; the individual
// seed modules under scripts/seeds/ are generated by scripts/gen-course-seeds.ts.
//
// Run on the server, as the service user, against the prod DB:
//   cd /srv/tapscore
//   sudo -u tapscore env DB_PATH=data/app.sqlite /usr/local/bin/bun run seed:prod
import { applyNamedSeeds } from './seed-lib';

// Real courses to seed into production. Add new generated seeds here.
const COURSE_SEEDS = [
    'linkopings', // Linköpings Golfklubb 1-18
    'landeryds-classic', // Landeryds GK — Classic
    'landeryds-masters', // Landeryds GK — Masters
    'landeryds-vesterby', // Landeryds GK — Vesterby Links
    'vreta-kloster', // Vreta Kloster GK — 18-hålsbanan
    'nsgk-klinga', // Norrköping Söderköping GK — Klinga
    'nsgk-hylinge', // Norrköping Söderköping GK — Hylinge 18-hål
    'mjolby', // Mjölby GK
];

const dbPath = process.env.DB_PATH || './data/app.sqlite';

console.log(`Seeding ${COURSE_SEEDS.length} courses into ${dbPath}...`);

try {
    await applyNamedSeeds(COURSE_SEEDS, { dbPath });
    console.log(`✅ Production seed complete — ${COURSE_SEEDS.length} courses`);
    process.exit(0);
} catch (e) {
    console.error('❌ Production seed failed:', e);
    process.exit(1);
}
