import { test, expect } from 'bun:test';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { shapeKey, uncoveredShapes } from '../ios/TapScoreTests/Create/format-shape-key';
import type { FormatDescriptor } from '../src/api/setup.gen';

const repoRoot = new URL('..', import.meta.url).pathname;
const generator = 'ios/TapScoreTests/Create/derive-web-fixtures.ts';
const fixtures = join(repoRoot, 'ios/TapScoreTests/Create/WebDraftFixtures.swift');

// The iOS create flow's parity proof rests on `WebDraftFixtures.swift`: drafts
// captured from the REAL web client (`src/create/setup.service.ts`) driven with
// the REAL server format catalog, which `CreateDraftParityTests` then asserts
// the native builder reproduces byte-for-byte.
//
// Both of its inputs live in this repo and neither is pinned by anything else.
// Change a format's declared ball requirement, or the web's composition rules,
// and the committed fixtures silently become expectations about a version of
// the web client that no longer exists — at which point the parity suite is
// green and proving nothing. Nobody would notice, because the fixtures are
// regenerated by hand and the Swift suite has no way to know they are stale.
//
// So: this runs the generator and fails on any diff. There is no CI here, so it
// hangs off the LOCAL gate (`bun run test` / `bun run test:scripts`) — which is
// why it lives beside `generate-swift.test.ts` rather than under `ios/`, where
// no bun runner would ever look at it.

test('the committed web-draft fixtures are what the generator produces now', async () => {
    const committed = readFileSync(fixtures, 'utf8');
    try {
        const proc = Bun.spawn(['bun', generator], {
            cwd: repoRoot,
            stdout: 'pipe',
            stderr: 'pipe',
        });
        const [out, err, code] = await Promise.all([
            new Response(proc.stdout).text(),
            new Response(proc.stderr).text(),
            proc.exited,
        ]);
        expect(err + out).not.toContain('no scenario covers');
        expect(code).toBe(0);

        const regenerated = readFileSync(fixtures, 'utf8');
        expect(
            regenerated === committed
                ? 'up to date'
                : `WebDraftFixtures.swift is STALE — the web client or the format catalog changed under it.\n` +
                  `Regenerate and review the diff (it IS the parity break):\n` +
                  `  bun run ${generator}`,
        ).toBe('up to date');
    } finally {
        // Leave the tree exactly as found, pass or fail: a test that rewrites a
        // committed file as a side effect turns "stale fixtures" into a commit
        // nobody read.
        writeFileSync(fixtures, committed);
    }
}, 120_000);

// The generator's own coverage guard only fires when somebody runs it. This
// asserts the same property against the COMMITTED file, so a newly declared
// format shape fails the local gate immediately rather than at the next
// regeneration.
test('every distinct format shape has a fixture scenario', async () => {
    const { registerBuiltInFormats } = await import('../server/domain/formats');
    const { clearFormats, formatCatalog } = await import('../server/domain/formats/plugin');
    clearFormats();
    registerBuiltInFormats();
    const all = JSON.parse(JSON.stringify(formatCatalog())) as FormatDescriptor[];

    // The descriptors the committed fixtures were generated against are carried
    // in the file itself (`catalogJSON`), narrowed to the formats used.
    const committed = readFileSync(fixtures, 'utf8');
    const catalogJSON = committed.split('static let catalogJSON = """\n')[1]?.split('\n    """')[0];
    expect(catalogJSON).toBeString();
    const covered = new Set(
        (JSON.parse(catalogJSON!) as FormatDescriptor[]).map((d) => shapeKey(d)),
    );

    const missing = uncoveredShapes(all, covered);
    expect(
        missing.size === 0
            ? 'covered'
            : `no fixture covers these format shapes: ${[...missing.values()]
                  .map((ids) => ids.join('/'))
                  .join(', ')} — add a scenario to ${generator} and regenerate.`,
    ).toBe('covered');
});
